name: Shared Version Check

on:
  workflow_call:
    inputs:
      workflow_token:
        description: "Token GitHub"
        required: false
        type: string
        default: ""

jobs:
  version-check:
    name: Check Version Increment & Tag
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Nécessaire pour git ls-remote / tags

      - name: Checkout central workflow repository
        uses: actions/checkout@v6
        with:
          repository: bedy90/shared-workflows
          path: .central-workflow
          ref: dev
          token: ${{ inputs.workflow_token || github.token }}

      - name: Version Module
        uses: ./.central-workflow/.github/actions/version
        with:
          workflow_token: ${{ inputs.workflow_token || github.token }}