name: Shared Docker Check

on:
  workflow_call:
    inputs:
      check_docker_compose:
        description: "Valider les fichiers docker-compose"
        required: false
        type: boolean
        default: false
      workflow_token:
        description: "GITHUB_TOKEN ou PAT pour accéder au dépôt partagé"
        required: false
        type: string
        default: ""

jobs:
  docker-validation:
    name: Docker Audit
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout central workflow repository
        uses: actions/checkout@v6
        with:
          repository: bedy90/shared-workflows
          path: .central-workflow
          ref: dev
          token: ${{ inputs.workflow_token || github.token }}

      - name: Docker Module
        uses: ./.central-workflow/.github/actions/docker
        with:
          check_docker_compose: "${{ inputs.check_docker_compose }}"
