name: Shared Security Check

on:
  workflow_call:
    inputs:
      workflow_token:
        description: "Token GitHub"
        required: false
        type: string
        default: ""
    secrets:
      gitleaks_license:
        description: "Licence Gitleaks"
        required: false

jobs:
  security-audit:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node 22.x
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"

      - name: Checkout central workflow repository
        uses: actions/checkout@v6
        with:
          repository: bedy90/shared-workflows
          path: .central-workflow
          ref: dev
          token: ${{ inputs.workflow_token || github.token }}

      - name: Security Module
        uses: ./.central-workflow/.github/actions/security
        with:
          central_path: ".central-workflow"
          workflow_token: ${{ inputs.workflow_token || github.token }}
          gitleaks_license: ${{ secrets.gitleaks_license }}
